### PR TITLE
[NEW] Support extra params in UserProfile

### PR DESCRIPTION
**Pull request by EugeneButusov**
update docs with extra field description in user profile

Please, let me know where I should place 'extra' field description. I think we should leave description for extra field because it's not too easy to understand the direct purpose of this thing. But I feel that I choose wrong place for this (because fields enum doesn't have any description in the brackets).

### CODE REVIEW

**Comment by EugeneButusov** [comment]
@vedi, in which place? In the same?

**Comment by vedi** [comment]
@EugeneButusov, so, let's change to "a dictionary contains additional info provided by social provider (FB: <params with short description>, Twitter: .... )"

**Comment by vedi** [comment]
@EugeneButusov, all is well. But sorry, you should move it to staging branch.

**Comment by EugeneButusov** [comment]
will be recreated with another branch (staging).

**Pull request closed without merging**
