### PR TITLE
[WIP] First version of Fyber integration example

### PR DESCRIPTION
**Pull request by sway**
First draft of the integration code of Fyber with Soomla for Unity and Android

TBD:
- [x] Review
- [x] Add iOS guide
- [x] Implement Soomla coin store mechanism on Android

### CODE REVIEW

**Comment by gurdotan** [comment]
@sway this is a good start.  I don't see any instantiation of SOOMLA Store.  You want to make sure it's in there somewhere.  Have you checked that the code compiles and runs?

**Comment by sway** [comment]
@gurdotan For the Unity example I just copied the UnityAds one (pretty much just moving stuff around into different delegate methods). Regarding Android, I am not at all familiar with the Soomla SDK so I did not include that part there. Please, feel free to amend the examples to include those pieces as well.

Regarding compiling and running, esp. on Android I (on purpose) omitted some UI related pieces to keep it as concise and integration-focused as possible, so I am quite sure this would not compile without additional changes.

**Comment by sway** [comment]
@gurdotan Updated the Android + Unity examples. iOS will come by the end of the week.

**Comment by sway** [comment]
@gurdotan iOS added, Unity updated, let me know what you think!

**Comment by gurdotan** [comment]
@sway thanks a lot, I'm going over this, might make a few structural changes.  I'll update you once it's up

**Pull request merged**
